//创建表空间  
CREATE TABLESPACE ts_myscott
	LOGGING
	DATAFILE 'e:\ORADATA\fundd_file.dbf' SIZE 40M
	EXTERT MANAGEMENT LOCAL;
ALTER DAEBASE DATEFILE 'e:\ORADATA\fundd_file.dbf' AUTOEXTEND ON NEXT 40M MAXSIZE UNLIMITED;
commit;

//创建用户
CREATE USER test_user PROFILE DEFAULT   
	IDENTIFIED BY test_user DEFAULT TABLESPACE USERS;
	ACCOUNT UNLOCK;
GRANT RESOURCE TO test_user;
GRANT create session TO test_user;

//创建表
CREATE TABLE test_user.DEPT(  
	DEPTNO NUMBER(6) PRIMARY KEY,
  	DName VARCHAR2(20) NOT NULL,  
  	  
)TABLESPACE ts_myscott;
INSERT INTO test_user.dept VALUES(10, 'ACCOUNTING', 'NEW YORK');
commit;

//创建索引
CREATE INDEX ts_myscott.xxx ON test_user.DEPT(DNAME) TABLESPACE ts_myscott;

//创建工资级别
CREATE TABLE tSALGRADE(  
	GRADE NUMBER,
	LOWSAL NUMBER,
	HISAL NUMBER,
)TABLESPACE ts_myscott;

//创建用户方案，通过MYSCOTTUSER1来访问数据库
CREATE USER "MYSCOTTUSER1" PROFILE "DEFAULT" IDENTIFIED BY "123456" DEFAULT TABLESPACE "USERS" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "MYSCOTTUSER1";
GRANT SELECT ANY TABLE TO "MYSCOTTUSER1";
GRANT DELETE ON est_user.DEPT TO "MYSCOTTUSER1";
...
commit;

